ARG IMAGE_VERSION

FROM alpine:${IMAGE_VERSION}

RUN apk update \
    && apk add --no-cache \
    git \
    && rm -rf /var/cache/apk/*

WORKDIR /home

ENTRYPOINT ["/bin/sh", "-c"]

CMD ["ash"]

#docker volume create --driver local --name volume-name
#docker build --no-cache --build-arg IMAGE_VERSION=latest --file Dockerfile.alpine --tag image-name:version .
#docker run --interactive --tty --mount type=volume,source=volume-name,target=/home --name container-name image-name:version
